import * as type from '@/types'
export const RAW_TOWER_OPTIONS = {
    sniper: {
        atk: 30,
        range: 300,
        atkspeed: 1,
        price: 25,
        totalValue: 25,
        buildingFields: ['forest', 'hill', 'grass'],
        color: 'hsl(0, 50%, 60%)',
        shortcut: '1',
    } as type.RawTower,
    ballista: {
        atk: 10,
        range: 75,
        atkspeed: 3,
        price: 25,
        totalValue: 25,
        buildingFields: ['forest', 'hill', 'grass'],
        color: 'hsl(318, 99%, 36%)',
        shortcut: '2',
    } as type.RawTower,
    laser: {
        atk: 3,
        range: 100,
        atkspeed: 10,
        price: 25,
        totalValue: 25,
        buildingFields: ['forest', 'hill', 'grass'],
        color: 'hsl(303, 50%, 70%)',
        shortcut: '3',
    } as type.RawTower,
    canonship: {
        atk: 15,
        range: 150,
        atkspeed: 2,
        price: 25,
        totalValue: 25,
        buildingFields: ['water'],
        color: 'hsl(32, 60%, 28%)',
        shortcut: '4',
    } as type.RawTower,
    bank: {
        atk: 1,
        range: 0,
        atkspeed: 0,
        price: 100,
        totalValue: 100,
        buildingFields: ['grass'],
        color: 'hsl(59, 100%, 59%)',
        shortcut: '5',
    } as type.RawTower,
    freezer: {
        atk: 10,
        range: 100,
        atkspeed: 2,
        price: 30,
        totalValue: 30,
        buildingFields: ['forest', 'hill', 'grass'],
        color: 'hsl(221, 100%, 67%)',
        shortcut: '6',
    } as type.RawTower,
}

export const TOWER_OPTIONS = Object.fromEntries(Object.entries(RAW_TOWER_OPTIONS).map(([k, v]) => [k, { ...v, type: k }])) as Record<type.TowerOption['type'], type.Tower>
